name: Distribution Builder
on:
  workflow_call:
    secrets:
      BUILD_GPG_PRIVATE_KEY:
        required: true
      BUILD_SSH_PRIVATE_KEY:
        required: true
      WEBDAV_PASSWD:
        required: true
      WEBDAV_USER:
        required: true
jobs:
  Arch:
    container:
      image: archlinux:latest
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
        - /etc/machine-id:/etc/machine-id
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event.pull_request.head.sha }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'push' }}
      - name: Init
        run: |
          pacman-key --init
          pacman-key --populate
          pacman-key -r AFAAFC4EF142770966FC4C805987B0C2A80EA669
          pacman-key --lsign-key AFAAFC4EF142770966FC4C805987B0C2A80EA669
          echo "[deepin]" >> /etc/pacman.conf
          echo "Server = https://deepin-community.github.io/arch-dde-repo" >> /etc/pacman.conf
          pacman -Sy deepin-keyring devtools-deepin-git base-devel --noconfirm --noprogressbar --needed
      - name: Build
        env:
          sha: ${{ github.GITHUB_SHA }}
        run: |
          name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
          git clone https://github.com/deepin-community/repo .repo
          sed -i "s|MAKEFLAGS=.*|MAKEFLAGS=-j$(nproc)|" /etc/makepkg.conf
          useradd -m user
          cp -r .repo/deepincn/git/$name /home/user/$name
          chown -R user /home/user/$name
          cd /home/user/$name
              deepin-x86_64-build -- -U user
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Arch
          path: /home/user/**/*.zst
  Arch-Upload:
    if: ${{ github.event_name == 'push' }}
    needs: [ Arch ]
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
        - /etc/machine-id:/etc/machine-id
    steps:
      - name: Init
        run: |
          pacman-key --init
          pacman-key --populate
          pacman-key -r AFAAFC4EF142770966FC4C805987B0C2A80EA669
          pacman-key --lsign-key AFAAFC4EF142770966FC4C805987B0C2A80EA669
          echo "[deepin]" >> /etc/pacman.conf
          echo "Server = https://deepin-community.github.io/arch-dde-repo" >> /etc/pacman.conf
          pacman -Sy openssh devtools --noconfirm --noprogressbar --needed
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.BUILD_GPG_PRIVATE_KEY }}
      - uses: webfactory/ssh-agent@v0.5.4
        name: Import SSH key
        with:
          ssh-private-key: ${{ secrets.BUILD_SSH_PRIVATE_KEY }}
      - run: git config --global user.email "ci@deepin.org"
      - run: git config --global user.name "deepin-ci"
      - name: Lock Database
        if: ${{ always() }}
        id: lock
        run: |
          for (( ; ; ))
          do
            rm -rf push-sleep || true
            git clone git@github.com:deepin-community/push-sleep.git -b arch
            cd push-sleep
            if [[ -f "lock" ]];
            then
              sleep $[ ( $RANDOM % 10 )  + 1 ]s
              continue
            else
              touch lock
              git add lock
              git commit -m "lock arch"
              git push || continue
              break
            fi
          done
      - name: Download all packages
        uses: actions/download-artifact@v3
        with:
          path: ./pkgs
      - name: Upload packages
        run: |
          find pkgs -name "*.zst" | xargs -I {} gpg --detach-sign --default-key builder {}
          git clone git@github.com:deepin-community/arch-dde-repo.git
          find pkgs -name "*.zst" | xargs -I {} cp {} arch-dde-repo
          find pkgs -name "*.sig" | xargs -I {} cp {} arch-dde-repo
          find pkgs -name "*.zst" | xargs -I {} repo-add -p -R arch-dde-repo/deepin.db.tar.xz {}
          cd arch-dde-repo
          git add .
          git commit --amend --no-edit
          git push -f
      - name: Unlock
        if: ${{ always() }}
        run: |
          cd push-sleep
          if [[ -f lock ]]; then
            git reset HEAD^
            rm -rf lock
            git push -f
          fi
      - name: wait for repo deploy
        run: |
          sleep 120
  Debian:
    if: ${{ false }}
    container:
      image: debian:testing
      options: --privileged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event.pull_request.head.sha }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'push' }}
      - name: Init
        run: |
          echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
          apt-get update
          apt-get install ca-certificates procps devscripts reprepro davfs2 -y
          echo "deb [trusted=yes] https://packages.mkacg.com/debian commit main" > /etc/apt/sources.list.d/commit.list
          apt-get update
      - uses: webfactory/ssh-agent@v0.5.4
        name: Import SSH key
        with:
          ssh-private-key: ${{ secrets.BUILD_SSH_PRIVATE_KEY }}
      - run: git config --global user.email "justforlxz@gmail.com"
      - run: git config --global user.name "justforlxz"
      - name: Build
        run: |
          mk-build-deps -i
          debuild -b -us -uc
      - name: Lock Database
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          for (( ; ; ))
          do
            rm -rf push-sleep || true
            git clone git@github.com:deepin-community/push-sleep.git -b debian
            cd push-sleep
            if [[ -f "lock" ]];
            then
              sleep $[ ( $RANDOM % 10 )  + 1 ]s
              continue
            else
              touch lock
              git add lock
              git commit -m "lock debian"
              git push || continue
            fi
          done
      - name: Mount webdav
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "https://webdav.mkacg.com ${{ secrets.WEBDAV_USER }} ${{ secrets.WEBDAV_PASSWD }}" >> /etc/davfs2/secrets
          echo "use_locks 0" >> /etc/davfs2/davfs2.conf
          mkdir repo
          mount -t davfs https://webdav.mkacg.com/ repo
      - name: Upload packages
        if: ${{ github.event_name == 'push' }}
        run: |
          cd repo/debian
          reprepro -C main includedeb commit ../../../*.deb
          #reprepro -C main includedsc commit ../../../*.dsc
      - name: Unmount webdav
        if: ${{ github.event_name == 'push' }}
        run: |
          umount -i -f -l repo
      - name: Unlock
        if: ${{ github.event_name == 'push' }}
        run: |
          cd push-sleep
          git reset HEAD^
          rm -rf lock
          git push -f
